services:
  mymongodb:
    image: mongo:latest
    container_name: "mymongodb"
    ports:
      - 27017:27017
  springboot-mongodb:
    image: total
    container_name: "total-mongodb"
    ports:
      - 8080:8080
    links:
      - mymongodb